### ISSUE TITLE
Generating rnc and xsd schemata for  uncostumized tei_odds, tei_svg, tei_math and tei_its fails.

### ISSUE THREAD

**Issue by aramiscd** [TEIC/Roma#23]
http://aramis.auriga.uberspace.de/public/cf7b9c8db3c55fa2e0f04d14c6aaac9d67dd64de79cceb544f785225876bf469.png

The other formats work fine though, including rng.

**Comment by lb42** [comment]
I can confirm that  schema generation for tei_svg by current online Roma is broken (both rng and rnc).  OTOH, if you use the corresponding online tools (e.g. teitorelaxng) or run the conversion within Oxygen, everything is fine. So I assume something need updating in the online roma tool.

**Comment by peterstadler** [comment]
The Roma web frontend sends these kind of requests to the [oxGarage](http://www.tei-c.org/oxgarage/) web service, so I was looking for the error there. It turned out, oxGarage was complaining about "Base URI {} is not an absolute URI". This cryptic message points at https://github.com/TEIC/TEI/blob/e546ef8b975db1abd7c047128ba0bc88dfacb7c6/P5/Exemplars/tei_svg.odd#L72 where there is only a relative URI to the file svg11.rng.

So, the workaround is to replace this URI with the absolute URI "http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/svg11.rng". 

Yet, I'm not sure whether this is an processing issue?

**Comment by lb42** [comment]
And indeed the current source of tei_svg.odd uses the full URL but it has been commented out for some reason. A bit of archaeology shows that this is all my fault: I seem to have made the change in May 2017 in commit https://github.com/TEIC/TEI/commit/93f69eb03a4e37a7cf24f6995ae1c7d989f18db4#diff-e70dc75b36abf6f47fe220d933da28c1 "misc typos". Probably I checked in a copy of the file I'd changed locally so as not to have to be online to run the test build and then forgot. Red face. Ink on tie. I have checked in a corrected version and rapped myself on knuckles.

**Comment by peterstadler** [comment]
Thanks @lb42 for digging!
[I replaced some more relative URIs in moduleRefs](https://github.com/TEIC/TEI/commit/f0d140e876bf859918ea2482626d42a9f446f123) as mentioned by @aramiscd – thanks for the notice!

NB: This is only fixed in the dev branch now and will be picked up by Roma and OxGarage not until the next update!
