### ISSUE TITLE
Rename Roma Repository to Roma Antiqua and Provide Deprecation Note

### ISSUE THREAD

**Issue by jamescummings** [TEIC/Roma#38]
The Roma Repository should be renamed since it stores Roma Antiqua, not RomaJS. (The latter does not need to be renamed IMHO.) 

Also there should be a deprecation note placed in the Readme.md file.

**Comment by peterstadler** [comment]
I'm a bit hesitant against renaming since this might cut off existing clones of the repo. (But maybe GitHub does some redirecting here? Anyway, I'm happy to be outvoted on this …)
My additional proposal would be to archive this repo to make it clear that we won't do any more work here. Could @TEITechnicalCouncil members put some thumbs up/down here, please, or discuss it at the next Council meeting?

**Comment by HelenaSabel** [comment]
I am definitely in favour of archiving the repo.

Concerning the renaming, GitHub does implement some redirections as stated here:

<blockquote>In addition to redirecting web traffic, all git clone, git fetch, or git push operations targeting the previous location will continue to function as if made on the new location. However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. </blockquote>

I am guessing that forks would be perfectly functional as well.
